名字：步数

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 11 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        key='${{ secrets.KEY }}'
        corpid='${{ secrets.CORPID }}'
        corpsecret='${{ secrets.CORPSECRET }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${key}
        ${corpsecret}
        ${corpid}
        ${user}
        ${pwd}
        ${step}
        EOF
